### ISSUE TITLE
[Bug] Delete k8sService do not trigger de-registering vpc lattice targets

### ISSUE THREAD

**Issue by zijun726911** [aws/aws-application-networking-k8s#331]
For example, if I have a full connectivity setup (set up gateway, httproute, services and deployment) 
if I do `kubectl delete service my-svc` ( my-svc is referenced in the httproute ), the controller didn't trigger de-registering vpc lattice target (I think expected behavior is it should)

We should investigate the root cause

**Comment by mikhail-aws** [comment]
is it fixed in #332 ?

**Comment by zijun726911** [comment]
I think that is a seperate issue, will double confirm

**Comment by zijun726911** [comment]
Just tried this test case https://github.com/aws/aws-application-networking-k8s/blob/9add0cfa73bfca7fb823d47c620b661db531c224/test/suites/integration/deregister_targets_test.go#L69

Not been fix, this bug still exist

**Comment by zijun726911** [comment]
https://github.com/aws/aws-application-networking-k8s/issues/331

Resaon this bug happen:  

Following controller could handle delete k8sService event:
- route_controller.go (build model failed will not invoke lattice api to de-registering targets)
- serviceexport_controller.go (build model failed will not invoke lattice api to de-registering targets)
- service_controller.go (do nothing to handle delete k8sService event )


Potential fix:
 in the service_controller.go, add finalizer when create k8sService, 
when handling k8sService deletion requestion, get all related routes name by `resourceMapper.ServiceToRoutes()`, use k8sService Name and route name to get all its targetGroup by datastore. de-registering targets all targets for these targetGroup

**Comment by zijun726911** [comment]
We had a refactoring that deleted the [service_controller.go](https://github.com/aws/aws-application-networking-k8s/pull/360/files#diff-00e81e75f6d3a8e448c8698e8838e914e508f7bb66e569da6fdd3d394baf96e5) deregistering targets logic and seems intend to use route_controller to do deregistering, but route_controller code path build target model failed

**Comment by zijun726911** [comment]
But I have a impression that even before this refactoring, the K8S service deletion already didn't work
